/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System.Data;
using OutSystems.RuntimeCommon;
using OutSystems.RuntimeCommon.ObfuscationProperties;

namespace OutSystems.HubEdition.RuntimePlatform.DBCompatibilityProxies.Adapters {
    /*
    *  This class is just to make it easier to translate and 
    *  maintain the compatibility in Java.
    */
    [DoNotObfuscate]
    internal class ADOAdaptersUtils {
        internal static IDbTransaction AdapterTransaction(IDbTransaction transaction) {
            return transaction;
        }

        internal static IDbDataParameter AdapterParameter(IDbDataParameter parameter) {
            return parameter;
        }

        internal static IDbCommand AdapterCommand(IDbCommand command) {
            return command;
        }

        public static IDbCommand GetADOCommand(IDbCommand command) {
            return command;
        }

        public static IDbTransaction GetADOTransaction(IDbTransaction transaction) {
            return transaction;
        }

        public static IDbDataParameter GetADOParameter(IDbDataParameter parameter) {
            return parameter;
        }

#if JAVA
        public static IDbDataParameter CreateADOParameter() {
            return null;
        }

#endif
    }
}
