/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using OutSystems.ObjectKeys;
using OutSystems.HubEdition.RuntimePlatform;
using OutSystems.RuntimeCommon;

namespace ssAddress_CS {

	public class DefaultValues {
		public static int ReferenceEntity_AddressType_ReferenceEntityAttribute_CreatedBy {
			get {
				return 0; 
			}
		}

		public static int ReferenceEntity_AddressType_ReferenceEntityAttribute_LastUpdatedBy {
			get {
				return 0; 
			}
		}

		public static long ReferenceEntity_Address_ReferenceEntityAttribute_CountryId {
			get {
				return 0L; 
			}
		}

		public static long ReferenceEntity_Address_ReferenceEntityAttribute_AddressTypeId {
			get {
				return 0L; 
			}
		}

		public static int ReferenceEntity_Address_ReferenceEntityAttribute_CreatedBy {
			get {
				return 0; 
			}
		}

		public static int ReferenceEntity_Address_ReferenceEntityAttribute_LastUpdatedBy {
			get {
				return 0; 
			}
		}

		public static long ReferenceActionFolder_AddressType_ReferenceActionInsideFolder_AddressType_GetOrCreateByLabel_Variables_ReferenceGenericOutputParameter_AddressTypeId {
			get {
				return 0L; 
			}
		}

		public static long ReferenceActionFolder_Address_ReferenceActionInsideFolder_Address_CreateOrUpdate_Variables_ReferenceGenericOutputParameter_AddressId {
			get {
				return 0L; 
			}
		}

	}
}
