/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Data;
using System.Web;
using System.Web.UI;
using System.Web.SessionState;
using System.Collections;
using System.Collections.Generic;
using System.Net;
using System.Security.Cryptography.X509Certificates;
using OutSystems.HubEdition.RuntimePlatform;
using OutSystems.HubEdition.RuntimePlatform.Db;
using OutSystems.Internal.Db;
using OutSystems.HubEdition.RuntimePlatform.Log;
using OutSystems.HubEdition.RuntimePlatform.Processes;
using OutSystems.ObjectKeys;
using OutSystems.RuntimeCommon;
using Pair = OutSystems.RuntimeCommon.Pair;

namespace ssAddress_CS {
	public partial class ExtendedActions {
		public static readonly ObjectKey rAnonymousKey = ObjectKey.Parse("0bApVE2NqE+q8EOBtnom8Q");
		public static readonly ObjectKey rRegisteredKey = ObjectKey.Parse("I1Fm79oZdUu8QBe+dLY9Cg");
		private static Random random = new Random();
		public static void AutoLogin(AppInfo info, SessionInfo session) {
			GenericExtendedActions.AutoLogin(info, session);
		} /// <summary>
		/// Action: CheckAnonymousRole
		/// </summary>

		public static void CheckAnonymousRole(HeContext heContext, int inParamUserId, out bool outParamHasRole) {
			outParamHasRole = false;

			outParamHasRole = true;
		}

		/// <summary>
		/// Action: CheckRegisteredRole
		/// </summary>

		public static void CheckRegisteredRole(HeContext heContext, int inParamUserId, out bool outParamHasRole) {
			outParamHasRole = false;

			int userId = heContext.Session.UserId;
			outParamHasRole = (userId != 0); 
		}

	}
}
