/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Linq;
using OutSystems.HubEdition.RuntimePlatform;
using OutSystems.HubEdition.RuntimePlatform.Db;
using OutSystems.Internal.Db;

using System.Text;
using System.Data;
using System.Collections.Generic;
using Newtonsoft.Json;
using OutSystems.RESTService;
using OutSystems.RESTService.Behaviors;
using OutSystems.RESTService.Controllers;
using OutSystems.ObjectKeys;
using OutSystems.HubEdition.RuntimePlatform.NewRuntime;


namespace ssAddress_CS.RestRecords {

	public class JSONENAddressTypeEntityRecord: AbstractRESTStructure<ENAddressTypeEntityRecord> {
		[JsonProperty("Id")]
		public long? AttrId;

		[JsonProperty("Label")]
		public string AttrLabel;

		[JsonProperty("Order")]
		public int? AttrOrder;

		[JsonProperty("Active")]
		public bool? AttrActive;

		[JsonProperty("CreatedDate")]
		public String AttrCreatedDate;

		[JsonProperty("CreatedBy")]
		public int? AttrCreatedBy;

		[JsonProperty("LastUpdatedDate")]
		public String AttrLastUpdatedDate;

		[JsonProperty("LastUpdatedBy")]
		public int? AttrLastUpdatedBy;

		public JSONENAddressTypeEntityRecord() {}

		public JSONENAddressTypeEntityRecord(ENAddressTypeEntityRecord s, IBehaviorsConfiguration config) {
			if (config.DefaultValuesBehavior == DefaultValuesBehavior.DontSend) {
				AttrId = (long?) s.ssId;
				AttrLabel = s.ssLabel;
				AttrOrder = ConvertToRestWithoutDefaults(s.ssOrder, 0);
				AttrActive = (bool?) s.ssActive;
				AttrCreatedDate = OutSystems.RESTService.Conversions.DateTimeToRestType(s.ssCreatedDate, config.DateTimeFormat);
				AttrCreatedBy = (int?) s.ssCreatedBy;
				AttrLastUpdatedDate = OutSystems.RESTService.Conversions.DateTimeToRestType(s.ssLastUpdatedDate, config.DateTimeFormat);
				AttrLastUpdatedBy = ConvertToRestWithoutDefaults(s.ssLastUpdatedBy, 0);
			} else {
				AttrId = (long?) s.ssId;
				AttrLabel = s.ssLabel;
				AttrOrder = (int?) s.ssOrder;
				AttrActive = (bool?) s.ssActive;
				AttrCreatedDate = OutSystems.RESTService.Conversions.DateTimeToRestType(s.ssCreatedDate, config.DateTimeFormat);
				AttrCreatedBy = (int?) s.ssCreatedBy;
				AttrLastUpdatedDate = OutSystems.RESTService.Conversions.DateTimeToRestType(s.ssLastUpdatedDate, config.DateTimeFormat);
				AttrLastUpdatedBy = (int?) s.ssLastUpdatedBy;
			}
		}

		public static Func<ssAddress_CS.RestRecords.JSONENAddressTypeEntityRecord, ENAddressTypeEntityRecord> ToStructureDelegate(IBehaviorsConfiguration config) {
			return (ssAddress_CS.RestRecords.JSONENAddressTypeEntityRecord s) => ToStructure(s, config);
		}
		public static ENAddressTypeEntityRecord ToStructure(ssAddress_CS.RestRecords.JSONENAddressTypeEntityRecord obj, IBehaviorsConfiguration config) {
			ENAddressTypeEntityRecord s = new ENAddressTypeEntityRecord(null);
			if (obj != null) {
				s.ssId = obj.AttrId == null ? 0L: obj.AttrId.Value;
				s.ssLabel = obj.AttrLabel == null ? "": obj.AttrLabel;
				s.ssOrder = obj.AttrOrder == null ? 0: obj.AttrOrder.Value;
				s.ssActive = obj.AttrActive == null ? true: obj.AttrActive.Value;
				s.ssCreatedDate = obj.AttrCreatedDate == null ? new DateTime(1900, 1, 1, 0, 0, 0): OutSystems.RESTService.Conversions.TextToDateTime(obj.AttrCreatedDate, config.DateTimeFormat);
				s.ssCreatedBy = obj.AttrCreatedBy == null ? 0: obj.AttrCreatedBy.Value;
				s.ssLastUpdatedDate = obj.AttrLastUpdatedDate == null ? new DateTime(1900, 1, 1, 0, 0, 0): OutSystems.RESTService.Conversions.TextToDateTime(obj.AttrLastUpdatedDate, config.DateTimeFormat);
				s.ssLastUpdatedBy = obj.AttrLastUpdatedBy == null ? 0: obj.AttrLastUpdatedBy.Value;
			}
			return s;
		}

		public static Func<ENAddressTypeEntityRecord, ssAddress_CS.RestRecords.JSONENAddressTypeEntityRecord> FromStructureDelegate(IBehaviorsConfiguration config) {
			return (ENAddressTypeEntityRecord s) => FromStructure(s, config);
		}
		public static ssAddress_CS.RestRecords.JSONENAddressTypeEntityRecord FromStructure(ENAddressTypeEntityRecord s, IBehaviorsConfiguration config) {
			return new ssAddress_CS.RestRecords.JSONENAddressTypeEntityRecord(s, config);
		}

	}



}