/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using OutSystems.Internal.Db;
using OutSystems.RuntimeCommon;
using OutSystems.RuntimeCommon.ObfuscationProperties;

namespace OutSystems.HubEdition.RuntimePlatform {

    [OutSystems.HubEdition.Extensibility.Data.Platform.QueryProvider.DatabaseProviderSpecificImplementationFor("Oracle")]
    [DoNotObfuscateType]
    internal class DBRuntimePlatformOracle : DBRuntimePlatform {
        public override int SaveEmail(Transaction tran, string @from, string to, string cc, string bcc, string subject, byte[] content, int contentlen,
                                      int activityId, int tenantId, int eSpaceId, string emailDefSSKey, bool storeContent, string messageId, bool enableEmails,
                                      string testEmails) {
            Command cmd = tran.CreateCommand(
                "DECLARE EMAILDEFINITIONID NUMBER(10,0);" +
                "BEGIN " +
                "SELECT ID INTO EMAILDEFINITIONID " +
                "FROM OSSYS_EMAIL_DEFINITION ED " +
                "WHERE ED.SS_KEY = @EMAILDEFSSKEY AND ED.IS_ACTIVE = 1 " + (eSpaceId != 0 ? "AND ED.ESPACE_ID = @ESPACEID " : "") + "AND ROWNUM <= 1;" +
                "INSERT INTO OSSYS_EMAIL (\"FROM\", \"TO\", \"CC\", \"BCC\", SUBJECT, CREATED, ACTIVITY_ID, TENANT_ID, EMAIL_DEFINITION_ID, STORE_CONTENT, IS_TEST_EMAIL, \"SIZE\", MESSAGE_ID) " +
                "VALUES(@EMAILFROM, @EMAILTO, @EMAILCC, @EMAILBCC, @SUBJECT, GETDATE(), @ACTIVITYID, @TENANTID, EMAILDEFINITIONID, @STORECONTENT, @ISTESTEMAIL ,@EMAILSIZE, @MESSAGEID) " +
                "RETURNING ID INTO @EMAILID;" +
                "END;");

            cmd.CreateParameter("@EMAILFROM", DbType.String, from);
            cmd.CreateParameter("@EMAILTO", DbType.String, enableEmails ? to : testEmails);
            cmd.CreateParameter("@EMAILCC", DbType.String, enableEmails ? cc : "");
            cmd.CreateParameter("@EMAILBCC", DbType.String, enableEmails ? bcc : "");
            cmd.CreateParameter("@ISTESTEMAIL", DbType.Boolean, !enableEmails);
            cmd.CreateParameter("@SUBJECT", DbType.String, subject);
            cmd.CreateParameter("@MESSAGEID", DbType.String, messageId);
            cmd.CreateParameter("@ACTIVITYID", DbType.Int32, activityId != 0 ? (object)activityId : null);
            cmd.CreateParameter("@TENANTID", DbType.Int32, tenantId != 0 ? (object)tenantId : null);
            cmd.CreateParameter("@EMAILDEFSSKEY", DbType.String, emailDefSSKey);
            if (eSpaceId != 0) {
                cmd.CreateParameter("@ESPACEID", DbType.Int32, eSpaceId);
            }
            cmd.CreateParameter("@STORECONTENT", DbType.Boolean, storeContent);
            cmd.CreateParameter("@EMAILSIZE", DbType.Int32, contentlen);

            DataParameter IdParamenter = cmd.CreateOutputParameter("@EMAILID", DbType.Int32);
            cmd.ExecuteNonQuery();
            int emailId = DataReaderUtils.SafeGet<int>(IdParamenter.Value);

            cmd = tran.CreateCommand(
                "INSERT INTO OSSYS_EMAIL_CONTENT (\"ID\", \"CONTENT\", \"TENANT_ID\") VALUES (@EMAILID, @CONTENT, @TENANTID)");

            cmd.CreateParameter("@EMAILID", DbType.Int32, emailId);
            cmd.CreateParameter("@CONTENT", DbType.Binary, content);
            cmd.CreateParameter("@TENANTID", DbType.Int32, tenantId != 0 ? (object)tenantId : null);
            cmd.ExecuteNonQuery();

            return emailId;
        }

        public override void GetDatabaseProviderAndVersion(out string database, out string version) {
            database = database = DatabaseAccess.ForCurrentDatabase.DatabaseServices.DatabaseConfiguration.DatabaseProvider.Properties.DisplayName;
            using (var trans = DatabaseAccess.ForCurrentDatabase.GetReadOnlyTransaction()) {
                using (var cmd = trans.CreateCommand("SELECT VERSION FROM PRODUCT_COMPONENT_VERSION WHERE UPPER(PRODUCT) LIKE '%DATABASE%'")) {
                    version = Convert.ToString(cmd.ExecuteScalar());
                }
            }
        }


        public override void UpdateSerialNumber(Transaction tran, string previousSerial, string newSerial) {
            string sql = "UPDATE ossys_parameter p1 set p1.host_serial = @currentSerial where upper(p1.host_serial) = @previousSerial AND NOT EXISTS (SELECT 1 FROM ossys_parameter p2 WHERE p1.name=p2.name AND  upper(p2.host_serial) = upper(@currentSerial))";
            using (var cmd = tran.CreateCommand(sql)) {
                cmd.CreateParameter("@previousSerial", DbType.String, previousSerial.ToUpper());
                cmd.CreateParameter("@currentSerial", DbType.String, newSerial);
                cmd.ExecuteNonQuery();
            }
        }


        public override int ExecuteNonQueryGetIdentity(Command cmd, string idColumnName) {
            bool plSqlNeeded = RuntimePlatformUtils.IsJava();

            cmd.CommandText = ((plSqlNeeded ? "begin " : String.Empty) + cmd.CommandText + " RETURNING " + idColumnName.ToUpper() + " INTO @id"
                + (plSqlNeeded ? " ;end;" : String.Empty));

            DataParameter IdParamenter = cmd.CreateOutputParameter("@id", DbType.Int32);
            cmd.ExecuteNonQuery();
            return DataReaderUtils.SafeGet<int>(IdParamenter.Value);
        }

        protected override void GetDbSpecificCatalogConfigurationParameters(Dictionary<string, object> parameters, IDataReader reader,
                string databaseName) {

            parameters.Add("Schema", databaseName.IsNullOrEmpty() ? DataReaderUtils.SafeGet<string>(reader["NAME"], string.Empty).Trim() : databaseName);
            parameters.Add("Tablespace", DataReaderUtils.SafeGet<string>(reader["DATATABLESPACE"], string.Empty).Trim());
            parameters.Add("TablespaceIndex", DataReaderUtils.SafeGet<string>(reader["INDEXTABLESPACE"], string.Empty).Trim());
        }

        protected override object UpdateTimerAndGetIsRunningSinceValue(Command updateCommand, bool isShared) {
            updateCommand.CommandText = "BEGIN " + updateCommand.CommandText + " RETURNING IS_RUNNING_SINCE INTO @NEW_IS_RUNNING_SINCE; END;";
            DataParameter IdParameter = updateCommand.CreateOutputParameter("@NEW_IS_RUNNING_SINCE", DbType.DateTime);
            updateCommand.ExecuteNonQuery();
            return IdParameter.Value;
        }

        protected override string GetPrecedentActivityIdSQL() {
            return @"SELECT ID
                     FROM (
                         SELECT ACT.ID, ACT.PRECEDENT_ACTIVITY_ID, ACT.ACTIVITY_DEF_ID, D.SS_KEY 
                         FROM OSSYS_BPM_ACTIVITY ACT
                         INNER JOIN OSSYS_BPM_ACTIVITY_DEFINITION D ON D.ID = ACT.ACTIVITY_DEF_ID
                         START WITH ACT.ID = @STARTID
                         CONNECT BY
                         PRIOR ACT.PRECEDENT_ACTIVITY_ID = ACT.ID AND PRIOR D.SS_KEY <> @TARGETKEY
                         )
                     WHERE SS_KEY = @TARGETKEY";
        }

        protected override string GetDequeueEventSQL() {
#if JAVA
            return "CALL {0}(@BATCHSIZE, @IP, @NULLDATE, @ACTIVITYID, @{1})".F(EventDequeueProcedureName, GetDequeueEventReaderParamName());
#else
            return Settings.GetBool(Settings.Configs.BPT_EnableImprovedDequeueEvent) ? EventDequeueProcedureNameImproved : base.GetDequeueEventSQL();
#endif
        }

        protected override string GetDequeueLightEventSQL() {
#if JAVA
            return "CALL {0}(@BATCHSIZE, @IP, @NULLDATE, @ACTIVITYID, @{1})".F(LightEventDequeueProcedureName, GetDequeueEventReaderParamName());
#else
            return base.GetDequeueLightEventSQL();
#endif
        }

        protected override string GetDequeueEventReaderParamName() {
            return "RECORDSET";
        }

        public override bool SelectLastLoginForUpdateNoWait(Transaction tran, int userID, int tenantID) {
            Command cmd = tran.CreateCommand("SELECT ID FROM OSSYS_USER " +
                                             "WHERE TENANT_ID = @TENANT_ID AND ID = @USER_ID " +
                                             "FOR UPDATE SKIP LOCKED");
            cmd.CreateParameter("@TENANT_ID", DbType.Int32, tenantID);
            cmd.CreateParameter("@USER_ID", DbType.Int32, userID);

            using (var reader = cmd.ExecuteReader("AttemptLogin operation (try get lock to update)", true)) {
                return reader.Read(); // Check if we locked a line or skipped
            }
        }
    }
}
