/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Web;
using System.Web.Caching;
using OutSystems.RuntimeCommon;

namespace OutSystems.HubEdition.RuntimePlatform {

    public class RuntimeCache {
        private static ICache instance = null;

        public static ICache Instance {
            get { return instance; }
        }

        static RuntimeCache(){
            instance = new ServerSideCache();
        }
    }

    public class ServerSideCache : ICache {

        public void Add(string key, object data, string fileDependencyName, int minutes) {
            this.Add(key, data, new CacheDependency(fileDependencyName), minutes);
        }

        public void Add(string key, object data, CacheDependency dependency, int minutes) {
            HttpRuntime.Cache.Add(key, data, dependency, DateTime.Now.AddMinutes(minutes), TimeSpan.Zero, System.Web.Caching.CacheItemPriority.Default, null);
        }
        
        public void Insert(string key, object data, string fileDependencyName, int minutes) {
            this.Insert(key, data, new CacheDependency(fileDependencyName), minutes);
        }

        public void Insert(string key, object data, CacheDependency dependency, int minutes) {
            HttpRuntime.Cache.Insert(key, data, dependency, DateTime.Now.AddMinutes(minutes), TimeSpan.Zero, System.Web.Caching.CacheItemPriority.Default, null);
        }

        public object Get(string key) {
            return HttpRuntime.Cache.Get(key);
        }
    }
}
