/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Diagnostics;
using OutSystems.RuntimeCommon;

namespace OutSystems.HubEdition.RuntimePlatform.Log {
	/// <summary>
	/// Summary description for serverlog.
	/// </summary>
    [Obsolete("Please use OutSystems.RuntimeCommon.Log.EventLogger instead.")]
    public class ServerLog {
        
	    public const string DefaultSource = OutSystems.RuntimeCommon.Log.EventLogger.DefaultSource;

		public ServerLog() {
            SetUp(DefaultSource);
        }

        public static void SetUp(string source) {
            OutSystems.RuntimeCommon.Log.EventLogger.SetUp(source);
		}

        public static void SetUp(string source, string disclamer) {
            OutSystems.RuntimeCommon.Log.EventLogger.SetUp(source, disclamer);
        }
        
        public static void CreateSource(string source) {
            OutSystems.RuntimeCommon.Log.EventLogger.CreateSource(source);
        }

		public static void Write( string message, EventLogEntryType type ) {
            OutSystems.RuntimeCommon.Log.EventLogger.Write(message, type);
		}

		public static void WriteInfo(string message) {
			Write(message, EventLogEntryType.Information);
		}

		public static void WriteError(string message) {
			Write(message, EventLogEntryType.Error);
		}

        public static void WriteError(Exception ex) {
            Write(ex.Message + Environment.NewLine + ex.StackTrace, EventLogEntryType.Error);
        }

		public static void WriteWarning(string message) {
			Write(message, EventLogEntryType.Warning);
		}

		public static void WriteDebug( string message ) {
			Write(message, EventLogEntryType.SuccessAudit);
		}
	}
}
