/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Net;
using System.Text;

namespace OutSystems.Internal.REST {

    /// <summary>
    /// Internal class used to store the context of a Rest Request.
    /// Should never be used directly. Use the OutSystems.RuntimePublic.REST.RestRequest class instead.
    /// </summary>
    public class RequestContext : IDisposable {

        [ThreadStatic]
        private static RequestContext currentContext;
        private RequestContext previousContext = null;

        private readonly string actionName;
        private readonly HttpWebRequest httpRequest;
        private string requestBodyAsText = null;
        private byte[] requestBodyAsBinary = null;

        /// <summary>
        /// Constructor for RequestContext.
        /// This class is for internal use only. Use the OutSystems.RuntimePublic.REST.RestRequest class instead.
        /// </summary>
        /// <param name="actionName"></param>
        /// <param name="httpRequest"></param>
        public RequestContext(string actionName, HttpWebRequest httpRequest) {
            this.previousContext = RequestContext.currentContext;
            RequestContext.currentContext = this;

            this.actionName = actionName;
            this.httpRequest = httpRequest;
        }

        /// <summary>
        /// Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged resources.
        /// </summary>
        public void Dispose() {
            RequestContext.currentContext = previousContext;
        }


        internal static RequestContext GetCurrent() {
            return RequestContext.currentContext;
        }

        /// <summary>
        /// Returns the name of the REST API Method that invoked the extension.
        /// </summary>
        public string GetActionName() {
            return actionName;
        }

        /// <summary>
        /// Returns the native HttpWebResponse object that resulted from the web request.
        /// </summary>
        public HttpWebRequest GetHttpWebRequest() {
            return httpRequest;
        }

        private static readonly Encoding DefaultRequestEncoding = System.Text.Encoding.UTF8;

        private Encoding GetRequestEncoding() {
            return DefaultRequestEncoding;
        }

        /// <summary>
        /// Returns the message body of the web response as a UTF-8 string.
        /// </summary>
        public string GetText() {
            if (requestBodyAsText == null && requestBodyAsBinary != null) {
                try {
                    requestBodyAsText = GetRequestEncoding().GetString(requestBodyAsBinary);
                } catch {
                    // Unable to c.onvert the byte[] into a string from UTF8, leave it null
                }
            }
            return requestBodyAsText;
        }

        /// <summary>
        /// Sets the message body of the web response.
        /// If the REST API Method has its 'Request Format' property set to 'Binary', no changes are made
        /// to the message body.
        /// </summary>
        /// <param name="text">The body of the web request.</param>
        public void SetText(string text) {
            this.requestBodyAsText = text;
            this.requestBodyAsBinary = null;
        }

        /// <summary>
        /// Returns the message body of the web response as binary content.
        /// </summary>
        public byte[] GetBinary() {
            if (requestBodyAsBinary == null && requestBodyAsText != null) {
                requestBodyAsBinary = GetRequestEncoding().GetBytes(requestBodyAsText);
            }
            return requestBodyAsBinary;
        }

        /// <summary>
        /// Sets the message body of the web response with binary content.
        /// </summary>
        /// <param name="bytes">The body of the web request.</param>
        public void SetBinary(byte[] bytes) {
            requestBodyAsBinary = bytes;
            requestBodyAsText = null;
        }
    }
}