/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

// Proxy for reference eSpace with name Business_CS and key zJcyDF1dVU69bZPpesujZQ
using System;
using System.Data;
using System.Reflection;
using System.Collections;
using System.Runtime.Serialization;
using OutSystems.ObjectKeys;
using OutSystems.RuntimeCommon;
using OutSystems.HubEdition.RuntimePlatform;
using System.Collections.Generic;
using System.Xml;
using OutSystems.HubEdition.RuntimePlatform.Db;
using OutSystems.Internal.Db;
using OutSystems.HubEdition.RuntimePlatform.Log;
using System.Web.UI;
using OutSystems.HubEdition.WebWidgets;
using OutSystems.HubEdition.RuntimePlatform.Web;
using ssAddress_CS;
namespace ssAddress_CS {
	/// <summary>
	/// Class: RsseSpaceBusiness_CS
	/// </summary>
	public class RsseSpaceBusiness_CS {
		protected static int _maxExtensionLogsPerRequest = OutSystems.HubEdition.RuntimePlatform.Settings.GetInt(OutSystems.HubEdition.RuntimePlatform.Settings.Configs.Log_MaxLogsPerRequest_Extension);
		public static int eSpaceId {
			get {
				return ssBusiness_CS.Global.eSpaceId;
			}
		}
		public static void MssOnSessionStart(HeContext heContext) {
			int oldCurrentESpaceId = heContext.CurrentESpaceId;
			try {
				heContext.CurrentESpaceId = ssBusiness_CS.Global.eSpaceId;
				if (RuntimePlatformUtils.TestAndSetProducerSession("Business_CS")) {
					ssBusiness_CS.Actions.ActionOnSessionStart(heContext);
				}
			} finally {
				heContext.CurrentESpaceId = oldCurrentESpaceId;
			}
		}


		public sealed partial class ENCountryEntity {
			public static string ViewName(int? tenant, string locale) {
				return ssBusiness_CS.ENCountryEntity.ViewName(tenant, locale);
			}
			public const int eSpaceId = ssBusiness_CS.Global.eSpaceId;
		} // ENCountryEntity


		public class Factory {
		}
		public class DefaultValues {
			public static int ReferenceEntity_Country_ReferenceEntityAttribute_CreatedBy {
				get {
					return ssBusiness_CS.DefaultValues.ReferenceEntity_Country_ReferenceEntityAttribute_CreatedBy; 
				}
			}
			public static int ReferenceEntity_Country_ReferenceEntityAttribute_LastUpdatedBy {
				get {
					return ssBusiness_CS.DefaultValues.ReferenceEntity_Country_ReferenceEntityAttribute_LastUpdatedBy; 
				}
			}
		}
		public static string CacheInvalidationSuffix {
			get {
				return ssBusiness_CS.AppUtils.Instance.CacheInvalidationSuffix;
			}
		}
	}
}
