/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace OutSystems.RuntimeCommon {
    public abstract class Configurations {
        public string Get(ConfigurationParameter param) {
            string result = RealGet(param);
            if (result == null) {
                result = param.DefaultValue;
            }
            return result;
        }

        public void Put(ConfigurationParameter param, string value) {
            RealPut(param, value);
        }

        protected abstract string RealGet(ConfigurationParameter param);
        protected abstract void RealPut(ConfigurationParameter param, string value);

        public int GetInt(ConfigurationParameter param) {
            return Convert.ToInt32(Get(param));
        }

        public void PutInt(ConfigurationParameter param, int value) {
            Put(param, Convert.ToString(value));
        }

        public bool GetBool(ConfigurationParameter param) {
            return Convert.ToBoolean(Get(param));
        }

        public void PutBool(ConfigurationParameter param, bool value) {
            Put(param, Convert.ToString(value));
        }
    }
}
