/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Data;
using MySql.Data.MySqlClient;
using OutSystems.HubEdition.Extensibility.Data;
using OutSystems.HubEdition.Extensibility.Data.ConfigurationService;
using OutSystems.HubEdition.Extensibility.Data.TransactionService;
using OutSystems.RuntimeCommon;
using OutSystems.RuntimeCommon.ObfuscationProperties;

namespace OutSystems.HubEdition.DatabaseProvider.MySQL.TransactionService {

    public class MySQLTransactionService : BaseTransactionService {

        public MySQLTransactionService(IDatabaseServices databaseServices) : base(databaseServices) { }


        protected override IsolationLevel IsolationLevel { get { return IsolationLevel.ReadUncommitted; } }

        protected override IDbConnection GetConnectionFromDriver() {
            return new MySqlConnection(DatabaseServices.DatabaseConfiguration.ConnectionString);
        }

        protected override void ReleaseAllPooledConnections() {
            
            MySqlConnection.ClearAllPools();
        }

        public override bool NeedsSeparateAdminConnection { get { return false; } }

    }
}
