/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using OutSystems.RuntimeCommon;
using System.Collections.Generic;

namespace OutSystems.Extensibility {
    public abstract class Configurator : OutSystemsExtensionPoint {

        public abstract String Name { get; }

        public virtual void AfterConfigurationSave() {
            // Does nothing by default, must be overridden if extension point wants to do anything (eg: copy or deploy some files)
            // Note: changes that can require a application server restart should be placed in the finish method
        } 
        
        public virtual void Finish() {
            // This is the last call that is made. No interaction with the application server is made after this inside the configuration tool
            // Does nothing by default, must be overridden if extension point wants to do anything (eg: copy or deploy some files)
        }

        public virtual void CreateMessageQueues(IList<LogType> queues) {
            // Does nothing by default, must be overridden if extension point needs to create message queues in the application server
        }

        public abstract void Configure(UserInteractions ui);

        public abstract void ConfigureWithDefaultValues();

        public virtual bool RequiresSoapHeadersSlowRetrieval() { return false; }
    }
}
